# -*- coding: utf-8 -*-
"""Hilmi Mufid_2505060046_latihan ke-10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qkuvHNPyhsMJAjAOxq2rqv8Q0qPTiDYo

1. Tuples
"""

# Pengerjaan nomer 1 A, B, C (dengan cara perubahan tuple ke list lalu ke tuple lagi)
mahasiswa = ("ACEP","9999","kedokteran")
print(f"tuple awal: {mahasiswa}\n")

mahasiswa_list = list(mahasiswa)
mahasiswa_list[2] = "Teknologi Informasi dan Elektro"
print(f"List mahasiswa:{mahasiswa_list}")

mahasiswa_list[2] = tuple(mahasiswa_list[2])
print(f"hasil :{mahasiswa_list}\n")

mahasiswa = ('ACEP',9999,'kedokteran\n')
print("-----------")
print(f"NIM : {mahasiswa[1]}")
print(f"Prodi : {mahasiswa_list[2]}\n")


# untuk pengerjaan hanya a dan c. Tampilkan data NIM dan Prodi
mahasiswa_univ = ("PONYO","8888","Sastra Listrik")

# memanmpilkan output
print("hasil nomer 1 a dan c :")
print(f"NIM : {mahasiswa_univ[1]}")
print(f"Prodi : {mahasiswa_univ[2]}")

"""2. Dictionary:"""

# Membuat dictionary
data_buah = {
    "apel":5000,
    "pisang":3000,
    "jeruk": 7000,
    "anggur": 1500
}

print(data_buah)
total=0

# Perulangan untuk menghitung total dan menampilkan harga
for nama_buah, harga in data_buah.items():
  print(f"harga {nama_buah} = {harga}")
  total += harga
print(f"harga total {total}")